table DimCustomer
	lineageTag: 15afdb88-490a-4cd8-80b8-a71377070e9a

	column CustomerSK
		dataType: int64
		formatString: 0
		lineageTag: c10032a7-390c-42ca-b315-47a71a25c668
		summarizeBy: none
		sourceColumn: CustomerSK

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 5e4b360c-109b-4ac2-98a4-b0500f3b417e
		summarizeBy: count
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: b0fa83dc-1b4f-4d44-bf4d-f1318c266a65
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: e6bf19e4-fa03-4685-bdab-f1fb12e26594
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: ee95c489-ef67-4c49-b167-150cdd9e8a18
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: c9b395e5-479e-4c47-9723-48405435b1b4
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 807a172a-ed56-4b01-b55f-116ddff047d8
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column JoinDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 63cc8007-5b44-45e6-a5a7-4f0985711d32
		summarizeBy: none
		sourceColumn: JoinDate

		variation Variation
			isDefault
			relationship: b3cb5cda-91d8-4798-8e0f-ba0020d83ed9
			defaultHierarchy: LocalDateTable_e4ac849f-e1d6-44d5-a9e7-d67239f56b34.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column City
		dataType: string
		lineageTag: 0a89def4-571c-48c1-a624-dbdecdb209a2
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 54cdaa46-4716-4420-8de0-0dda8fe5bc0d
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: f15e52b5-9012-49b0-bf53-2ccf4825f88c
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column CustomerTenureYears
		dataType: int64
		formatString: 0
		lineageTag: 3496a5c3-4d4c-449e-a464-a681bbebdef5
		summarizeBy: sum
		sourceColumn: CustomerTenureYears

		annotation SummarizationSetBy = Automatic

	column JoinYear
		dataType: int64
		formatString: 0
		lineageTag: 0f102917-efab-47e8-900a-b546c49517bc
		summarizeBy: sum
		sourceColumn: JoinYear

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		queryGroup: 'Dimension table'
		source =
				let
				  Source = Sql.Database("localhost", "RetailDW"),
				  #"Navigation 1" = Source{[Schema = "warehouse", Item = "DimCustomer"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Navigation 1",{"_LoadedAt", "warehouse.FactReturns", "warehouse.FactSales"})
				in
				  #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

