table DimRegion
	lineageTag: 2a71ecc4-7808-4a42-bd14-527a0b9cd2dc

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: 7628452a-7fae-451a-aa17-77b2b828417c
		summarizeBy: count
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: 89dc2c52-8d7c-42fe-9550-02602a65186e
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	column RegionSK
		dataType: int64
		formatString: 0
		lineageTag: bba638ae-ec29-4585-8661-96083391153c
		summarizeBy: none
		sourceColumn: RegionSK

		annotation SummarizationSetBy = Automatic

	partition DimRegion = m
		mode: import
		queryGroup: 'Dimension table'
		source =
				let
				  Source = Sql.Database("localhost", "RetailDW"),
				  #"Navigation 1" = Source{[Schema = "warehouse", Item = "DimRegion"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Navigation 1",{"warehouse.FactInventory", "warehouse.FactReturns", "warehouse.FactSales", "_LoadedAt"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

