table DimStore
	lineageTag: beb611e3-2df7-4516-94e7-f5ca53e79964

	column StoreSK
		dataType: int64
		formatString: 0
		lineageTag: 615a4253-5e04-4f28-96e1-4bd36cd4050b
		summarizeBy: none
		sourceColumn: StoreSK

		annotation SummarizationSetBy = Automatic

	column StoreID
		dataType: int64
		formatString: 0
		lineageTag: fdd29385-62e9-42d3-b1ef-e0f58b6f99be
		summarizeBy: count
		sourceColumn: StoreID

		annotation SummarizationSetBy = Automatic

	column StoreName
		dataType: string
		lineageTag: 82ab25ee-a6d9-4b1c-be9e-e7346d96cac1
		summarizeBy: none
		sourceColumn: StoreName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 043cdd77-eef8-494f-9e24-e050279896a1
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b88d55d8-e280-4cb6-9e84-88aaa64dc567
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 25498d05-379f-4386-9f70-0b2f85ae9971
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column StoreType
		dataType: string
		lineageTag: 499a43e3-b036-47dc-a5fa-0be9ebda42f3
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2354b58c-dcac-4253-bd70-fe33b70a92a2
		summarizeBy: none
		sourceColumn: OpenDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SquareFootage
		dataType: int64
		formatString: 0
		lineageTag: 677324b8-4cad-42e5-885e-f2af92ef73b4
		summarizeBy: sum
		sourceColumn: SquareFootage

		annotation SummarizationSetBy = Automatic

	column StoreSize
		dataType: string
		lineageTag: ee0fe9ee-561b-4b9e-82a3-2b208bf0bc76
		summarizeBy: none
		sourceColumn: StoreSize

		annotation SummarizationSetBy = Automatic

	column YearsOpen
		dataType: int64
		formatString: 0
		lineageTag: fe0f8dca-9fb6-4aab-ae0f-c7f976761761
		summarizeBy: sum
		sourceColumn: YearsOpen

		annotation SummarizationSetBy = Automatic

	hierarchy 'Region Hierarchy'
		lineageTag: 86432c39-1e5c-4247-9cc4-21071d262e45

		level Region
			lineageTag: 14291998-aa45-46d0-a659-8b8c33e026f4
			column: Region

		level State
			lineageTag: bb775f86-6fc6-44c4-8ae3-4ff98323d3a2
			column: State

		level City
			lineageTag: 42de0507-6ddc-4484-8fdf-a91b56493956
			column: City

		level StoreName
			lineageTag: 47d57105-8dff-461b-9fd6-5be7f3335fe1
			column: StoreName

	partition DimStore = m
		mode: import
		queryGroup: 'Dimension table'
		source =
				let
				  Source = Sql.Database("localhost", "RetailDW"),
				  #"Navigation 1" = Source{[Schema = "warehouse", Item = "DimStore"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Navigation 1",{"_LoadedAt", "warehouse.FactInventory", "warehouse.FactReturns", "warehouse.FactSales"})
				in
				  #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

